version: '3.2'
services:

  app_producer:
    build:
        context: ./app_producer
        dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=dev
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=demo.orders.new
    volumes:
        - ./app_producer:/go/src/app_producer
    networks:
      - developer

  app_consumer:
    build:
        context: ./app_consumer_log
        dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=dev
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=demo.orders.new
      - CONSUMER_GROUP=logger
    volumes:
        - ./app_consumer_log:/go/src/app_consumer_log
    networks:
      - developer

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - developer

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,PLAINTEXT_HOST://kafka:9092,
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
      - "moby:127.0.0.1"
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    networks:
      - developer

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks: 
      - developer
    depends_on:
      - kafka
      - zookeeper
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:9092

networks:
  developer: